name = "OIFITS"
uuid = "53eb397e-dec1-5dcf-8dc9-2db916067267"
version = "2.0.0"
authors = ["Éric Thiébaut <https://github.com/emmt>"]

[deps]
AstroFITS = "34e54ef0-c5bf-48ab-9e5d-cca51f35ed77"

[compat]
Aqua = "0.8.14"
AstroFITS = "1.1"
Printf = "<0.0.1, 1"
Random = "<0.0.1, 1"
Test = "<0.0.1, 1"
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random", "Printf"]
