name = "OIFITS"
uuid = "53eb397e-dec1-5dcf-8dc9-2db916067267"
authors = ["Éric Thiébaut <https://github.com/emmt>"]
version = "1.1.0"

[deps]
EasyFITS = "a977f4a2-36a7-4172-89e7-19c2726f82e5"

[compat]
EasyFITS = "0.5.13, 0.6, 0.7"
julia = "1.6"

[extras]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random", "Printf"]
